//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LabServerModel", "FK_DoctorConnectMapping_Doctor", "Doctor", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataRepository.Doctor), "DoctorConnectMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataRepository.DoctorConnectMapping), true)]
[assembly: EdmRelationshipAttribute("LabServerModel", "FK_DoctorConnectMapping_LabClient", "LabClient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataRepository.LabClient), "DoctorConnectMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataRepository.DoctorConnectMapping), true)]
[assembly: EdmRelationshipAttribute("LabServerModel", "FK_Examination_LabClient", "LabClient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataRepository.LabClient), "Examination", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataRepository.Examination), true)]
[assembly: EdmRelationshipAttribute("LabServerModel", "FK_LabConnectMapping_LabClient", "LabClient", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DataRepository.LabClient), "LabConnectMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataRepository.LabConnectMapping), true)]
[assembly: EdmRelationshipAttribute("LabServerModel", "FK_LabConnectMapping_LabClientConnected", "LabClient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataRepository.LabClient), "LabConnectMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataRepository.LabConnectMapping), true)]
[assembly: EdmRelationshipAttribute("LabServerModel", "FK_LabnetAccount_LabClient", "LabClient", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DataRepository.LabClient), "LabnetAccount", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DataRepository.LabnetAccount), true)]

#endregion

namespace DataRepository
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class LabnetServerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new LabnetServerEntities object using the connection string found in the 'LabnetServerEntities' section of the application configuration file.
        /// </summary>
        public LabnetServerEntities() : base("name=LabnetServerEntities", "LabnetServerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LabnetServerEntities object.
        /// </summary>
        public LabnetServerEntities(string connectionString) : base(connectionString, "LabnetServerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new LabnetServerEntities object.
        /// </summary>
        public LabnetServerEntities(EntityConnection connection) : base(connection, "LabnetServerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Doctor> Doctors
        {
            get
            {
                if ((_Doctors == null))
                {
                    _Doctors = base.CreateObjectSet<Doctor>("Doctors");
                }
                return _Doctors;
            }
        }
        private ObjectSet<Doctor> _Doctors;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Examination> Examinations
        {
            get
            {
                if ((_Examinations == null))
                {
                    _Examinations = base.CreateObjectSet<Examination>("Examinations");
                }
                return _Examinations;
            }
        }
        private ObjectSet<Examination> _Examinations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LabnetAccount> LabnetAccounts
        {
            get
            {
                if ((_LabnetAccounts == null))
                {
                    _LabnetAccounts = base.CreateObjectSet<LabnetAccount>("LabnetAccounts");
                }
                return _LabnetAccounts;
            }
        }
        private ObjectSet<LabnetAccount> _LabnetAccounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DoctorConnectMapping> DoctorConnectMappings
        {
            get
            {
                if ((_DoctorConnectMappings == null))
                {
                    _DoctorConnectMappings = base.CreateObjectSet<DoctorConnectMapping>("DoctorConnectMappings");
                }
                return _DoctorConnectMappings;
            }
        }
        private ObjectSet<DoctorConnectMapping> _DoctorConnectMappings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LabConnectMapping> LabConnectMappings
        {
            get
            {
                if ((_LabConnectMappings == null))
                {
                    _LabConnectMappings = base.CreateObjectSet<LabConnectMapping>("LabConnectMappings");
                }
                return _LabConnectMappings;
            }
        }
        private ObjectSet<LabConnectMapping> _LabConnectMappings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LabClient> LabClients
        {
            get
            {
                if ((_LabClients == null))
                {
                    _LabClients = base.CreateObjectSet<LabClient>("LabClients");
                }
                return _LabClients;
            }
        }
        private ObjectSet<LabClient> _LabClients;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Doctors EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDoctors(Doctor doctor)
        {
            base.AddObject("Doctors", doctor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Examinations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExaminations(Examination examination)
        {
            base.AddObject("Examinations", examination);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LabnetAccounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabnetAccounts(LabnetAccount labnetAccount)
        {
            base.AddObject("LabnetAccounts", labnetAccount);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DoctorConnectMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDoctorConnectMappings(DoctorConnectMapping doctorConnectMapping)
        {
            base.AddObject("DoctorConnectMappings", doctorConnectMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LabConnectMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabConnectMappings(LabConnectMapping labConnectMapping)
        {
            base.AddObject("LabConnectMappings", labConnectMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LabClients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLabClients(LabClient labClient)
        {
            base.AddObject("LabClients", labClient);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="length">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> GenerateConnectionCode(Nullable<global::System.Int32> length)
        {
            ObjectParameter lengthParameter;
            if (length.HasValue)
            {
                lengthParameter = new ObjectParameter("Length", length);
            }
            else
            {
                lengthParameter = new ObjectParameter("Length", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<global::System.String>("GenerateConnectionCode", lengthParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="length">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> GenerateExaminationNumber(Nullable<global::System.Int32> length)
        {
            ObjectParameter lengthParameter;
            if (length.HasValue)
            {
                lengthParameter = new ObjectParameter("Length", length);
            }
            else
            {
                lengthParameter = new ObjectParameter("Length", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<global::System.String>("GenerateExaminationNumber", lengthParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabServerModel", Name="Doctor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Doctor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Doctor object.
        /// </summary>
        /// <param name="doctorId">Initial value of the DoctorId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Doctor CreateDoctor(global::System.Int32 doctorId, global::System.String userName, global::System.String password, global::System.String name)
        {
            Doctor doctor = new Doctor();
            doctor.DoctorId = doctorId;
            doctor.UserName = userName;
            doctor.Password = password;
            doctor.Name = name;
            return doctor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DoctorId
        {
            get
            {
                return _DoctorId;
            }
            set
            {
                if (_DoctorId != value)
                {
                    OnDoctorIdChanging(value);
                    ReportPropertyChanging("DoctorId");
                    _DoctorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DoctorId");
                    OnDoctorIdChanged();
                }
            }
        }
        private global::System.Int32 _DoctorId;
        partial void OnDoctorIdChanging(global::System.Int32 value);
        partial void OnDoctorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthDay
        {
            get
            {
                return _BirthDay;
            }
            set
            {
                OnBirthDayChanging(value);
                ReportPropertyChanging("BirthDay");
                _BirthDay = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthDay");
                OnBirthDayChanged();
            }
        }
        private global::System.String _BirthDay;
        partial void OnBirthDayChanging(global::System.String value);
        partial void OnBirthDayChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_DoctorConnectMapping_Doctor", "DoctorConnectMapping")]
        public EntityCollection<DoctorConnectMapping> DoctorConnectMappings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DoctorConnectMapping>("LabServerModel.FK_DoctorConnectMapping_Doctor", "DoctorConnectMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DoctorConnectMapping>("LabServerModel.FK_DoctorConnectMapping_Doctor", "DoctorConnectMapping", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabServerModel", Name="DoctorConnectMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DoctorConnectMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DoctorConnectMapping object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="labId">Initial value of the LabId property.</param>
        /// <param name="clientDoctorId">Initial value of the ClientDoctorId property.</param>
        /// <param name="connectionCode">Initial value of the ConnectionCode property.</param>
        public static DoctorConnectMapping CreateDoctorConnectMapping(global::System.Int32 id, global::System.Int32 labId, global::System.Int32 clientDoctorId, global::System.String connectionCode)
        {
            DoctorConnectMapping doctorConnectMapping = new DoctorConnectMapping();
            doctorConnectMapping.Id = id;
            doctorConnectMapping.LabId = labId;
            doctorConnectMapping.ClientDoctorId = clientDoctorId;
            doctorConnectMapping.ConnectionCode = connectionCode;
            return doctorConnectMapping;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DoctorId
        {
            get
            {
                return _DoctorId;
            }
            set
            {
                OnDoctorIdChanging(value);
                ReportPropertyChanging("DoctorId");
                _DoctorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoctorId");
                OnDoctorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DoctorId;
        partial void OnDoctorIdChanging(Nullable<global::System.Int32> value);
        partial void OnDoctorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LabId
        {
            get
            {
                return _LabId;
            }
            set
            {
                OnLabIdChanging(value);
                ReportPropertyChanging("LabId");
                _LabId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LabId");
                OnLabIdChanged();
            }
        }
        private global::System.Int32 _LabId;
        partial void OnLabIdChanging(global::System.Int32 value);
        partial void OnLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientDoctorId
        {
            get
            {
                return _ClientDoctorId;
            }
            set
            {
                OnClientDoctorIdChanging(value);
                ReportPropertyChanging("ClientDoctorId");
                _ClientDoctorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientDoctorId");
                OnClientDoctorIdChanged();
            }
        }
        private global::System.Int32 _ClientDoctorId;
        partial void OnClientDoctorIdChanging(global::System.Int32 value);
        partial void OnClientDoctorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectionCode
        {
            get
            {
                return _ConnectionCode;
            }
            set
            {
                OnConnectionCodeChanging(value);
                ReportPropertyChanging("ConnectionCode");
                _ConnectionCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectionCode");
                OnConnectionCodeChanged();
            }
        }
        private global::System.String _ConnectionCode;
        partial void OnConnectionCodeChanging(global::System.String value);
        partial void OnConnectionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConnectionState
        {
            get
            {
                return _ConnectionState;
            }
            set
            {
                OnConnectionStateChanging(value);
                ReportPropertyChanging("ConnectionState");
                _ConnectionState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectionState");
                OnConnectionStateChanged();
            }
        }
        private Nullable<global::System.Int32> _ConnectionState;
        partial void OnConnectionStateChanging(Nullable<global::System.Int32> value);
        partial void OnConnectionStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateConnected
        {
            get
            {
                return _DateConnected;
            }
            set
            {
                OnDateConnectedChanging(value);
                ReportPropertyChanging("DateConnected");
                _DateConnected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateConnected");
                OnDateConnectedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateConnected;
        partial void OnDateConnectedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateConnectedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_DoctorConnectMapping_Doctor", "Doctor")]
        public Doctor Doctor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Doctor>("LabServerModel.FK_DoctorConnectMapping_Doctor", "Doctor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Doctor>("LabServerModel.FK_DoctorConnectMapping_Doctor", "Doctor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Doctor> DoctorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Doctor>("LabServerModel.FK_DoctorConnectMapping_Doctor", "Doctor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Doctor>("LabServerModel.FK_DoctorConnectMapping_Doctor", "Doctor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_DoctorConnectMapping_LabClient", "LabClient")]
        public LabClient LabClient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_DoctorConnectMapping_LabClient", "LabClient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_DoctorConnectMapping_LabClient", "LabClient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LabClient> LabClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_DoctorConnectMapping_LabClient", "LabClient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LabClient>("LabServerModel.FK_DoctorConnectMapping_LabClient", "LabClient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabServerModel", Name="Examination")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Examination : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Examination object.
        /// </summary>
        /// <param name="examinationId">Initial value of the ExaminationId property.</param>
        /// <param name="examinationNumber">Initial value of the ExaminationNumber property.</param>
        /// <param name="labId">Initial value of the LabId property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        public static Examination CreateExamination(global::System.Int32 examinationId, global::System.String examinationNumber, global::System.Int32 labId, global::System.DateTime createdDate, global::System.Int32 status)
        {
            Examination examination = new Examination();
            examination.ExaminationId = examinationId;
            examination.ExaminationNumber = examinationNumber;
            examination.LabId = labId;
            examination.CreatedDate = createdDate;
            examination.Status = status;
            return examination;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ExaminationId
        {
            get
            {
                return _ExaminationId;
            }
            set
            {
                if (_ExaminationId != value)
                {
                    OnExaminationIdChanging(value);
                    ReportPropertyChanging("ExaminationId");
                    _ExaminationId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ExaminationId");
                    OnExaminationIdChanged();
                }
            }
        }
        private global::System.Int32 _ExaminationId;
        partial void OnExaminationIdChanging(global::System.Int32 value);
        partial void OnExaminationIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExaminationNumber
        {
            get
            {
                return _ExaminationNumber;
            }
            set
            {
                OnExaminationNumberChanging(value);
                ReportPropertyChanging("ExaminationNumber");
                _ExaminationNumber = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExaminationNumber");
                OnExaminationNumberChanged();
            }
        }
        private global::System.String _ExaminationNumber;
        partial void OnExaminationNumberChanging(global::System.String value);
        partial void OnExaminationNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LabId
        {
            get
            {
                return _LabId;
            }
            set
            {
                OnLabIdChanging(value);
                ReportPropertyChanging("LabId");
                _LabId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LabId");
                OnLabIdChanged();
            }
        }
        private global::System.Int32 _LabId;
        partial void OnLabIdChanging(global::System.Int32 value);
        partial void OnLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.Int32 _Status;
        partial void OnStatusChanging(global::System.Int32 value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PatientName
        {
            get
            {
                return _PatientName;
            }
            set
            {
                OnPatientNameChanging(value);
                ReportPropertyChanging("PatientName");
                _PatientName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PatientName");
                OnPatientNameChanged();
            }
        }
        private global::System.String _PatientName;
        partial void OnPatientNameChanging(global::System.String value);
        partial void OnPatientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BirthDay
        {
            get
            {
                return _BirthDay;
            }
            set
            {
                OnBirthDayChanging(value);
                ReportPropertyChanging("BirthDay");
                _BirthDay = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BirthDay");
                OnBirthDayChanged();
            }
        }
        private global::System.String _BirthDay;
        partial void OnBirthDayChanging(global::System.String value);
        partial void OnBirthDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClientPartnerId
        {
            get
            {
                return _ClientPartnerId;
            }
            set
            {
                OnClientPartnerIdChanging(value);
                ReportPropertyChanging("ClientPartnerId");
                _ClientPartnerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientPartnerId");
                OnClientPartnerIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ClientPartnerId;
        partial void OnClientPartnerIdChanging(Nullable<global::System.Int32> value);
        partial void OnClientPartnerIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ClientDoctorId
        {
            get
            {
                return _ClientDoctorId;
            }
            set
            {
                OnClientDoctorIdChanging(value);
                ReportPropertyChanging("ClientDoctorId");
                _ClientDoctorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientDoctorId");
                OnClientDoctorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ClientDoctorId;
        partial void OnClientDoctorIdChanging(Nullable<global::System.Int32> value);
        partial void OnClientDoctorIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_Examination_LabClient", "LabClient")]
        public LabClient LabClient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_Examination_LabClient", "LabClient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_Examination_LabClient", "LabClient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LabClient> LabClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_Examination_LabClient", "LabClient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LabClient>("LabServerModel.FK_Examination_LabClient", "LabClient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabServerModel", Name="LabClient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LabClient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LabClient object.
        /// </summary>
        /// <param name="labId">Initial value of the LabId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="amount">Initial value of the Amount property.</param>
        public static LabClient CreateLabClient(global::System.Int32 labId, global::System.String name, global::System.String url, global::System.Decimal amount)
        {
            LabClient labClient = new LabClient();
            labClient.LabId = labId;
            labClient.Name = name;
            labClient.Url = url;
            labClient.Amount = amount;
            return labClient;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LabId
        {
            get
            {
                return _LabId;
            }
            set
            {
                if (_LabId != value)
                {
                    OnLabIdChanging(value);
                    ReportPropertyChanging("LabId");
                    _LabId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LabId");
                    OnLabIdChanged();
                }
            }
        }
        private global::System.Int32 _LabId;
        partial void OnLabIdChanging(global::System.Int32 value);
        partial void OnLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Amount
        {
            get
            {
                return _Amount;
            }
            set
            {
                OnAmountChanging(value);
                ReportPropertyChanging("Amount");
                _Amount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amount");
                OnAmountChanged();
            }
        }
        private global::System.Decimal _Amount;
        partial void OnAmountChanging(global::System.Decimal value);
        partial void OnAmountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_DoctorConnectMapping_LabClient", "DoctorConnectMapping")]
        public EntityCollection<DoctorConnectMapping> DoctorConnectMappings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DoctorConnectMapping>("LabServerModel.FK_DoctorConnectMapping_LabClient", "DoctorConnectMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DoctorConnectMapping>("LabServerModel.FK_DoctorConnectMapping_LabClient", "DoctorConnectMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_Examination_LabClient", "Examination")]
        public EntityCollection<Examination> Examinations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Examination>("LabServerModel.FK_Examination_LabClient", "Examination");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Examination>("LabServerModel.FK_Examination_LabClient", "Examination", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_LabConnectMapping_LabClient", "LabConnectMapping")]
        public EntityCollection<LabConnectMapping> LabConnectMappings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LabConnectMapping>("LabServerModel.FK_LabConnectMapping_LabClient", "LabConnectMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LabConnectMapping>("LabServerModel.FK_LabConnectMapping_LabClient", "LabConnectMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_LabConnectMapping_LabClientConnected", "LabConnectMapping")]
        public EntityCollection<LabConnectMapping> LabConnectMappings1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LabConnectMapping>("LabServerModel.FK_LabConnectMapping_LabClientConnected", "LabConnectMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LabConnectMapping>("LabServerModel.FK_LabConnectMapping_LabClientConnected", "LabConnectMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_LabnetAccount_LabClient", "LabnetAccount")]
        public EntityCollection<LabnetAccount> LabnetAccounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LabnetAccount>("LabServerModel.FK_LabnetAccount_LabClient", "LabnetAccount");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LabnetAccount>("LabServerModel.FK_LabnetAccount_LabClient", "LabnetAccount", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabServerModel", Name="LabConnectMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LabConnectMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LabConnectMapping object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="labId">Initial value of the LabId property.</param>
        /// <param name="clientLabId">Initial value of the ClientLabId property.</param>
        /// <param name="connectionCode">Initial value of the ConnectionCode property.</param>
        /// <param name="connectionState">Initial value of the ConnectionState property.</param>
        public static LabConnectMapping CreateLabConnectMapping(global::System.Int32 id, global::System.Int32 labId, global::System.Int32 clientLabId, global::System.String connectionCode, global::System.Int32 connectionState)
        {
            LabConnectMapping labConnectMapping = new LabConnectMapping();
            labConnectMapping.Id = id;
            labConnectMapping.LabId = labId;
            labConnectMapping.ClientLabId = clientLabId;
            labConnectMapping.ConnectionCode = connectionCode;
            labConnectMapping.ConnectionState = connectionState;
            return labConnectMapping;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LabId
        {
            get
            {
                return _LabId;
            }
            set
            {
                OnLabIdChanging(value);
                ReportPropertyChanging("LabId");
                _LabId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LabId");
                OnLabIdChanged();
            }
        }
        private global::System.Int32 _LabId;
        partial void OnLabIdChanging(global::System.Int32 value);
        partial void OnLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ConnectedLabId
        {
            get
            {
                return _ConnectedLabId;
            }
            set
            {
                OnConnectedLabIdChanging(value);
                ReportPropertyChanging("ConnectedLabId");
                _ConnectedLabId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectedLabId");
                OnConnectedLabIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ConnectedLabId;
        partial void OnConnectedLabIdChanging(Nullable<global::System.Int32> value);
        partial void OnConnectedLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientLabId
        {
            get
            {
                return _ClientLabId;
            }
            set
            {
                OnClientLabIdChanging(value);
                ReportPropertyChanging("ClientLabId");
                _ClientLabId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClientLabId");
                OnClientLabIdChanged();
            }
        }
        private global::System.Int32 _ClientLabId;
        partial void OnClientLabIdChanging(global::System.Int32 value);
        partial void OnClientLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ConnectionCode
        {
            get
            {
                return _ConnectionCode;
            }
            set
            {
                OnConnectionCodeChanging(value);
                ReportPropertyChanging("ConnectionCode");
                _ConnectionCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ConnectionCode");
                OnConnectionCodeChanged();
            }
        }
        private global::System.String _ConnectionCode;
        partial void OnConnectionCodeChanging(global::System.String value);
        partial void OnConnectionCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ConnectionState
        {
            get
            {
                return _ConnectionState;
            }
            set
            {
                OnConnectionStateChanging(value);
                ReportPropertyChanging("ConnectionState");
                _ConnectionState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConnectionState");
                OnConnectionStateChanged();
            }
        }
        private global::System.Int32 _ConnectionState;
        partial void OnConnectionStateChanging(global::System.Int32 value);
        partial void OnConnectionStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateConnected
        {
            get
            {
                return _DateConnected;
            }
            set
            {
                OnDateConnectedChanging(value);
                ReportPropertyChanging("DateConnected");
                _DateConnected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateConnected");
                OnDateConnectedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateConnected;
        partial void OnDateConnectedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateConnectedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_LabConnectMapping_LabClient", "LabClient")]
        public LabClient LabClient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClient", "LabClient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClient", "LabClient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LabClient> LabClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClient", "LabClient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClient", "LabClient", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_LabConnectMapping_LabClientConnected", "LabClient")]
        public LabClient LabClient1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClientConnected", "LabClient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClientConnected", "LabClient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LabClient> LabClient1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClientConnected", "LabClient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LabClient>("LabServerModel.FK_LabConnectMapping_LabClientConnected", "LabClient", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabServerModel", Name="LabnetAccount")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LabnetAccount : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LabnetAccount object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="domain">Initial value of the Domain property.</param>
        /// <param name="role">Initial value of the Role property.</param>
        public static LabnetAccount CreateLabnetAccount(global::System.Int32 userId, global::System.String userName, global::System.String password, global::System.String domain, global::System.Int32 role)
        {
            LabnetAccount labnetAccount = new LabnetAccount();
            labnetAccount.UserId = userId;
            labnetAccount.UserName = userName;
            labnetAccount.Password = password;
            labnetAccount.Domain = domain;
            labnetAccount.Role = role;
            return labnetAccount;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LabId
        {
            get
            {
                return _LabId;
            }
            set
            {
                OnLabIdChanging(value);
                ReportPropertyChanging("LabId");
                _LabId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LabId");
                OnLabIdChanged();
            }
        }
        private Nullable<global::System.Int32> _LabId;
        partial void OnLabIdChanging(Nullable<global::System.Int32> value);
        partial void OnLabIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Domain
        {
            get
            {
                return _Domain;
            }
            set
            {
                OnDomainChanging(value);
                ReportPropertyChanging("Domain");
                _Domain = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Domain");
                OnDomainChanged();
            }
        }
        private global::System.String _Domain;
        partial void OnDomainChanging(global::System.String value);
        partial void OnDomainChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Role
        {
            get
            {
                return _Role;
            }
            set
            {
                OnRoleChanging(value);
                ReportPropertyChanging("Role");
                _Role = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Role");
                OnRoleChanged();
            }
        }
        private global::System.Int32 _Role;
        partial void OnRoleChanging(global::System.Int32 value);
        partial void OnRoleChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabServerModel", "FK_LabnetAccount_LabClient", "LabClient")]
        public LabClient LabClient
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabnetAccount_LabClient", "LabClient").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabnetAccount_LabClient", "LabClient").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LabClient> LabClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LabClient>("LabServerModel.FK_LabnetAccount_LabClient", "LabClient");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LabClient>("LabServerModel.FK_LabnetAccount_LabClient", "LabClient", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
