//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModel.ModelStrings", typeof(ModelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Kết Nối.
        /// </summary>
        internal static string VMDoctorConnectMapping_DateConnected {
            get {
                return ResourceManager.GetString("VMDoctorConnectMapping_DateConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string VMDoctorConnectMapping_Email {
            get {
                return ResourceManager.GetString("VMDoctorConnectMapping_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng XN.
        /// </summary>
        internal static string VMDoctorConnectMapping_LabName {
            get {
                return ResourceManager.GetString("VMDoctorConnectMapping_LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số BN Trong Ngày.
        /// </summary>
        internal static string VMDoctorConnectMapping_PatientInDay {
            get {
                return ResourceManager.GetString("VMDoctorConnectMapping_PatientInDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số BN Trong Tháng.
        /// </summary>
        internal static string VMDoctorConnectMapping_PatientInMonth {
            get {
                return ResourceManager.GetString("VMDoctorConnectMapping_PatientInMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện Thoại.
        /// </summary>
        internal static string VMDoctorConnectMapping_PhoneNumber {
            get {
                return ResourceManager.GetString("VMDoctorConnectMapping_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm Sinh.
        /// </summary>
        internal static string VMExmaination_BirthDay {
            get {
                return ResourceManager.GetString("VMExmaination_BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Gửi .
        /// </summary>
        internal static string VMExmaination_CreatedDate {
            get {
                return ResourceManager.GetString("VMExmaination_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã XN.
        /// </summary>
        internal static string VMExmaination_ExaminationNumber {
            get {
                return ResourceManager.GetString("VMExmaination_ExaminationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phòng XN .
        /// </summary>
        internal static string VMExmaination_LabClient {
            get {
                return ResourceManager.GetString("VMExmaination_LabClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bệnh Nhân.
        /// </summary>
        internal static string VMExmaination_PatientName {
            get {
                return ResourceManager.GetString("VMExmaination_PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Điện Thoại.
        /// </summary>
        internal static string VMExmaination_Phone {
            get {
                return ResourceManager.GetString("VMExmaination_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng Thái.
        /// </summary>
        internal static string VMExmaination_Status {
            get {
                return ResourceManager.GetString("VMExmaination_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem KQ.
        /// </summary>
        internal static string VMExmaination_ViewResult {
            get {
                return ResourceManager.GetString("VMExmaination_ViewResult", resourceCulture);
            }
        }
    }
}
