//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartnerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartnerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PartnerStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string PanelSearch_Search {
            get {
                return ResourceManager.GetString("PanelSearch_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật Lab Gửi Mẫu.
        /// </summary>
        internal static string PartnerEdit_Title {
            get {
                return ResourceManager.GetString("PartnerEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string PartnerInsert_Active {
            get {
                return ResourceManager.GetString("PartnerInsert_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        internal static string PartnerInsert_Address {
            get {
                return ResourceManager.GetString("PartnerInsert_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string PartnerInsert_Button_Add {
            get {
                return ResourceManager.GetString("PartnerInsert_Button_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        internal static string PartnerInsert_Button_Add_TestSection {
            get {
                return ResourceManager.GetString("PartnerInsert_Button_Add_TestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Mới.
        /// </summary>
        internal static string PartnerInsert_Button_Cancel {
            get {
                return ResourceManager.GetString("PartnerInsert_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string PartnerInsert_Button_Save {
            get {
                return ResourceManager.GetString("PartnerInsert_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Liên Kết.
        /// </summary>
        internal static string PartnerInsert_ConnectionCode {
            get {
                return ResourceManager.GetString("PartnerInsert_ConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PartnerInsert_Email {
            get {
                return ResourceManager.GetString("PartnerInsert_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string PartnerInsert_Fax {
            get {
                return ResourceManager.GetString("PartnerInsert_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string PartnerInsert_GridColumn_Delete {
            get {
                return ResourceManager.GetString("PartnerInsert_GridColumn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string PartnerInsert_GridColumn_Price {
            get {
                return ResourceManager.GetString("PartnerInsert_GridColumn_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Xét Nghiệm.
        /// </summary>
        internal static string PartnerInsert_GridColumn_TestName {
            get {
                return ResourceManager.GetString("PartnerInsert_GridColumn_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách xét nghiệm của lab gửi mẫu.
        /// </summary>
        internal static string PartnerInsert_GridColumn_Title {
            get {
                return ResourceManager.GetString("PartnerInsert_GridColumn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Kết Nối.
        /// </summary>
        internal static string PartnerInsert_IsConnected {
            get {
                return ResourceManager.GetString("PartnerInsert_IsConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Lab.
        /// </summary>
        internal static string PartnerInsert_Name {
            get {
                return ResourceManager.GetString("PartnerInsert_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Lab đã tồn tại.
        /// </summary>
        internal static string PartnerInsert_NameError {
            get {
                return ResourceManager.GetString("PartnerInsert_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mới.
        /// </summary>
        internal static string PartnerInsert_New {
            get {
                return ResourceManager.GetString("PartnerInsert_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi Chú.
        /// </summary>
        internal static string PartnerInsert_Note {
            get {
                return ResourceManager.GetString("PartnerInsert_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Lab.
        /// </summary>
        internal static string PartnerInsert_Owner {
            get {
                return ResourceManager.GetString("PartnerInsert_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn xét nghiệm cho Lab.
        /// </summary>
        internal static string PartnerInsert_PartnerCostError {
            get {
                return ResourceManager.GetString("PartnerInsert_PartnerCostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Điện Thoại.
        /// </summary>
        internal static string PartnerInsert_Phone {
            get {
                return ResourceManager.GetString("PartnerInsert_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xét Nghiệm.
        /// </summary>
        internal static string PartnerInsert_Test {
            get {
                return ResourceManager.GetString("PartnerInsert_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá XN.
        /// </summary>
        internal static string PartnerInsert_TestPrice {
            get {
                return ResourceManager.GetString("PartnerInsert_TestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm XN.
        /// </summary>
        internal static string PartnerInsert_TestSection {
            get {
                return ResourceManager.GetString("PartnerInsert_TestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá Nhóm.
        /// </summary>
        internal static string PartnerInsert_TestSectionPrice {
            get {
                return ResourceManager.GetString("PartnerInsert_TestSectionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Lab Gởi Mẫu.
        /// </summary>
        internal static string PartnerInsert_Title {
            get {
                return ResourceManager.GetString("PartnerInsert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Lab.
        /// </summary>
        internal static string PartnerSearch_GridPartnerName {
            get {
                return ResourceManager.GetString("PartnerSearch_GridPartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string PartnerSearch_IsActive {
            get {
                return ResourceManager.GetString("PartnerSearch_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Lab.
        /// </summary>
        internal static string PartnerSearch_Name {
            get {
                return ResourceManager.GetString("PartnerSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Lab Gửi Mẫu.
        /// </summary>
        internal static string PartnerSearch_Title {
            get {
                return ResourceManager.GetString("PartnerSearch_Title", resourceCulture);
            }
        }
    }
}
