//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DoctorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DoctorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DoctorStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Bác Sĩ.
        /// </summary>
        internal static string DoctorEdit_Title {
            get {
                return ResourceManager.GetString("DoctorEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string DoctorInsert_Address {
            get {
                return ResourceManager.GetString("DoctorInsert_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        internal static string DoctorInsert_BankAccount {
            get {
                return ResourceManager.GetString("DoctorInsert_BankAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string DoctorInsert_ButtonNew {
            get {
                return ResourceManager.GetString("DoctorInsert_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string DoctorInsert_ButtonSave {
            get {
                return ResourceManager.GetString("DoctorInsert_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Hoa hồng.
        /// </summary>
        internal static string DoctorInsert_Commission {
            get {
                return ResourceManager.GetString("DoctorInsert_Commission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Liên Kết.
        /// </summary>
        internal static string DoctorInsert_ConnectionCode {
            get {
                return ResourceManager.GetString("DoctorInsert_ConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string DoctorInsert_Email {
            get {
                return ResourceManager.GetString("DoctorInsert_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bác sĩ này đã tồn tại.
        /// </summary>
        internal static string DoctorInsert_ErrorExist {
            get {
                return ResourceManager.GetString("DoctorInsert_ErrorExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string DoctorInsert_Fax {
            get {
                return ResourceManager.GetString("DoctorInsert_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        internal static string DoctorInsert_IsActive {
            get {
                return ResourceManager.GetString("DoctorInsert_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Bác Sĩ.
        /// </summary>
        internal static string DoctorInsert_Name {
            get {
                return ResourceManager.GetString("DoctorInsert_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        internal static string DoctorInsert_Note {
            get {
                return ResourceManager.GetString("DoctorInsert_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string DoctorInsert_Phone {
            get {
                return ResourceManager.GetString("DoctorInsert_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Bác Sĩ.
        /// </summary>
        internal static string DoctorInsert_Title {
            get {
                return ResourceManager.GetString("DoctorInsert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string DoctorSearch_ButtonSearch {
            get {
                return ResourceManager.GetString("DoctorSearch_ButtonSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên BS.
        /// </summary>
        internal static string DoctorSearch_GridDoctorName {
            get {
                return ResourceManager.GetString("DoctorSearch_GridDoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Bác Sĩ.
        /// </summary>
        internal static string DoctorSearch_Name {
            get {
                return ResourceManager.GetString("DoctorSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Bác Sĩ.
        /// </summary>
        internal static string DoctorSearch_Title {
            get {
                return ResourceManager.GetString("DoctorSearch_Title", resourceCulture);
            }
        }
    }
}
