//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PanelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PanelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PanelStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên panel này đã tồn tại..
        /// </summary>
        internal static string PanelCreate_NameError {
            get {
                return ResourceManager.GetString("PanelCreate_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm XN.
        /// </summary>
        internal static string PanelInsert_ButtonAdd {
            get {
                return ResourceManager.GetString("PanelInsert_ButtonAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới.
        /// </summary>
        internal static string PanelInsert_ButtonNew {
            get {
                return ResourceManager.GetString("PanelInsert_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string PanelInsert_ButtonSave {
            get {
                return ResourceManager.GetString("PanelInsert_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string PanelInsert_Description {
            get {
                return ResourceManager.GetString("PanelInsert_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string PanelInsert_GridRemove {
            get {
                return ResourceManager.GetString("PanelInsert_GridRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Xét Nghiệm.
        /// </summary>
        internal static string PanelInsert_GridTestName {
            get {
                return ResourceManager.GetString("PanelInsert_GridTestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm.
        /// </summary>
        internal static string PanelInsert_GridTestSection {
            get {
                return ResourceManager.GetString("PanelInsert_GridTestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string PanelInsert_IsActive {
            get {
                return ResourceManager.GetString("PanelInsert_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Panel.
        /// </summary>
        internal static string PanelInsert_Name {
            get {
                return ResourceManager.GetString("PanelInsert_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xét nghiệm.
        /// </summary>
        internal static string PanelInsert_TestName {
            get {
                return ResourceManager.GetString("PanelInsert_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạo Panel.
        /// </summary>
        internal static string PanelInsert_Title {
            get {
                return ResourceManager.GetString("PanelInsert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Panel.
        /// </summary>
        internal static string PanelSearch_GridPanelName {
            get {
                return ResourceManager.GetString("PanelSearch_GridPanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật.
        /// </summary>
        internal static string PanelSearch_GridUpdateLink {
            get {
                return ResourceManager.GetString("PanelSearch_GridUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Panel.
        /// </summary>
        internal static string PanelSearch_Name {
            get {
                return ResourceManager.GetString("PanelSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm.
        /// </summary>
        internal static string PanelSearch_Search {
            get {
                return ResourceManager.GetString("PanelSearch_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Panel.
        /// </summary>
        internal static string PanelSearch_Title {
            get {
                return ResourceManager.GetString("PanelSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật Panel.
        /// </summary>
        internal static string PanelUpdate_Title {
            get {
                return ResourceManager.GetString("PanelUpdate_Title", resourceCulture);
            }
        }
    }
}
