//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DomainModel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên Bác sĩ.
        /// </summary>
        internal static string VMDoctor_NameRequired {
            get {
                return ResourceManager.GetString("VMDoctor_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Bác Sĩ.
        /// </summary>
        internal static string VMDoctorSearch_DoctorName {
            get {
                return ResourceManager.GetString("VMDoctorSearch_DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string VMDoctorSearch_Email {
            get {
                return ResourceManager.GetString("VMDoctorSearch_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string VMPanel_Cost {
            get {
                return ResourceManager.GetString("VMPanel_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô Tả.
        /// </summary>
        internal static string VMPanel_Description {
            get {
                return ResourceManager.GetString("VMPanel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa.
        /// </summary>
        internal static string VMPanel_IsDelete {
            get {
                return ResourceManager.GetString("VMPanel_IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string VMPanel_IsEnable {
            get {
                return ResourceManager.GetString("VMPanel_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên Panel.
        /// </summary>
        internal static string VMPanel_NameRequired {
            get {
                return ResourceManager.GetString("VMPanel_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Panel.
        /// </summary>
        internal static string VMPanel_PanelName {
            get {
                return ResourceManager.GetString("VMPanel_PanelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm XN.
        /// </summary>
        internal static string VMPanel_Section {
            get {
                return ResourceManager.GetString("VMPanel_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Xét Nghiệm.
        /// </summary>
        internal static string VMPanel_TestName {
            get {
                return ResourceManager.GetString("VMPanel_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên Panel.
        /// </summary>
        internal static string VMPanelSearch_NameRequired {
            get {
                return ResourceManager.GetString("VMPanelSearch_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ.
        /// </summary>
        internal static string VMPartner_AddressRequired {
            get {
                return ResourceManager.GetString("VMPartner_AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email.
        /// </summary>
        internal static string VMPartner_EmailRequired {
            get {
                return ResourceManager.GetString("VMPartner_EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên.
        /// </summary>
        internal static string VMPartner_NameRequired {
            get {
                return ResourceManager.GetString("VMPartner_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        internal static string VMPartnerSearch_Address {
            get {
                return ResourceManager.GetString("VMPartnerSearch_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string VMPartnerSearch_Email {
            get {
                return ResourceManager.GetString("VMPartnerSearch_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Lab.
        /// </summary>
        internal static string VMPartnerSearch_PartnerName {
            get {
                return ResourceManager.GetString("VMPartnerSearch_PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện Thoại.
        /// </summary>
        internal static string VMPartnerSearch_Phone {
            get {
                return ResourceManager.GetString("VMPartnerSearch_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa Chỉ.
        /// </summary>
        internal static string VMPatient_Address {
            get {
                return ResourceManager.GetString("VMPatient_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập địa chỉ.
        /// </summary>
        internal static string VMPatient_Address_RequireMessage {
            get {
                return ResourceManager.GetString("VMPatient_Address_RequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuổi.
        /// </summary>
        internal static string VMPatient_Age {
            get {
                return ResourceManager.GetString("VMPatient_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập ngày sinh.
        /// </summary>
        internal static string VMPatient_Birthday_RequireMessage {
            get {
                return ResourceManager.GetString("VMPatient_Birthday_RequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ Tên.
        /// </summary>
        internal static string VMPatient_Name {
            get {
                return ResourceManager.GetString("VMPatient_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập họ tên.
        /// </summary>
        internal static string VMPatient_Name_RequireMessage {
            get {
                return ResourceManager.GetString("VMPatient_Name_RequireMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Điện Thoại.
        /// </summary>
        internal static string VMPatient_Phone {
            get {
                return ResourceManager.GetString("VMPatient_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string VMPatientTest_Cost {
            get {
                return ResourceManager.GetString("VMPatientTest_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string VMPatientTest_IsEnable {
            get {
                return ResourceManager.GetString("VMPatientTest_IsEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panel XN.
        /// </summary>
        internal static string VMPatientTest_Panel {
            get {
                return ResourceManager.GetString("VMPatientTest_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm XN.
        /// </summary>
        internal static string VMPatientTest_Section {
            get {
                return ResourceManager.GetString("VMPatientTest_Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên XN.
        /// </summary>
        internal static string VMPatientTest_TestName {
            get {
                return ResourceManager.GetString("VMPatientTest_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác Minh.
        /// </summary>
        internal static string VMPatientTestResult_Approved {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        internal static string VMPatientTestResult_Index {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Xét Nghiệm.
        /// </summary>
        internal static string VMPatientTestResult_Name {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSTB.
        /// </summary>
        internal static string VMPatientTestResult_Range {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết Quả.
        /// </summary>
        internal static string VMPatientTestResult_Result {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tình Trạng.
        /// </summary>
        internal static string VMPatientTestResult_Status {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn Vị.
        /// </summary>
        internal static string VMPatientTestResult_Unit {
            get {
                return ResourceManager.GetString("VMPatientTestResult_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mô tả XN.
        /// </summary>
        internal static string VMTest_DescriptionRequired {
            get {
                return ResourceManager.GetString("VMTest_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên XN.
        /// </summary>
        internal static string VMTest_NameRequired {
            get {
                return ResourceManager.GetString("VMTest_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập nhóm XN.
        /// </summary>
        internal static string VMTest_TestSectionNameRequired {
            get {
                return ResourceManager.GetString("VMTest_TestSectionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên XN.
        /// </summary>
        internal static string VMTestSearch_NameRequired {
            get {
                return ResourceManager.GetString("VMTestSearch_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả XN.
        /// </summary>
        internal static string VMTestSearch_TestDescription {
            get {
                return ResourceManager.GetString("VMTestSearch_TestDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên XN.
        /// </summary>
        internal static string VMTestSearch_TestName {
            get {
                return ResourceManager.GetString("VMTestSearch_TestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSBT.
        /// </summary>
        internal static string VMTestSearch_TestRange {
            get {
                return ResourceManager.GetString("VMTestSearch_TestRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm XN.
        /// </summary>
        internal static string VMTestSearch_TestSectionName {
            get {
                return ResourceManager.GetString("VMTestSearch_TestSectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        internal static string VMTestSearch_TestUnit {
            get {
                return ResourceManager.GetString("VMTestSearch_TestUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích hoạt.
        /// </summary>
        internal static string VMTestSection_Active {
            get {
                return ResourceManager.GetString("VMTestSection_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string VMTestSection_Cost {
            get {
                return ResourceManager.GetString("VMTestSection_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô Tả.
        /// </summary>
        internal static string VMTestSection_Description {
            get {
                return ResourceManager.GetString("VMTestSection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mô tả nhóm XN.
        /// </summary>
        internal static string VMTestSection_DescriptionRequired {
            get {
                return ResourceManager.GetString("VMTestSection_DescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên.
        /// </summary>
        internal static string VMTestSection_Name {
            get {
                return ResourceManager.GetString("VMTestSection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên nhóm XN.
        /// </summary>
        internal static string VMTestSection_NameRequired {
            get {
                return ResourceManager.GetString("VMTestSection_NameRequired", resourceCulture);
            }
        }
    }
}
