//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TestStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string TestCreate_Cost {
            get {
                return ResourceManager.GetString("TestCreate_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string TestCreate_Description {
            get {
                return ResourceManager.GetString("TestCreate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ số lớn.
        /// </summary>
        internal static string TestCreate_HighIndex {
            get {
                return ResourceManager.GetString("TestCreate_HighIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập chỉ số bé và chỉ số lớn.
        /// </summary>
        internal static string TestCreate_IndexError {
            get {
                return ResourceManager.GetString("TestCreate_IndexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string TestCreate_IsActive {
            get {
                return ResourceManager.GetString("TestCreate_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In đậm.
        /// </summary>
        internal static string TestCreate_IsBold {
            get {
                return ResourceManager.GetString("TestCreate_IsBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ số bé.
        /// </summary>
        internal static string TestCreate_LowIndex {
            get {
                return ResourceManager.GetString("TestCreate_LowIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên XN.
        /// </summary>
        internal static string TestCreate_Name {
            get {
                return ResourceManager.GetString("TestCreate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mới.
        /// </summary>
        internal static string TestCreate_New {
            get {
                return ResourceManager.GetString("TestCreate_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSBT.
        /// </summary>
        internal static string TestCreate_Range {
            get {
                return ResourceManager.GetString("TestCreate_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string TestCreate_Save {
            get {
                return ResourceManager.GetString("TestCreate_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        internal static string TestCreate_SortOrder {
            get {
                return ResourceManager.GetString("TestCreate_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm XN.
        /// </summary>
        internal static string TestCreate_TestSection {
            get {
                return ResourceManager.GetString("TestCreate_TestSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Xét Nghiệm.
        /// </summary>
        internal static string TestCreate_Title {
            get {
                return ResourceManager.GetString("TestCreate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        internal static string TestCreate_Unit {
            get {
                return ResourceManager.GetString("TestCreate_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật Xét Nghiệm.
        /// </summary>
        internal static string TestEdit_Title {
            get {
                return ResourceManager.GetString("TestEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xét nghiệm này đã tồn tại..
        /// </summary>
        internal static string Test_Create_NameError {
            get {
                return ResourceManager.GetString("Test_Create_NameError", resourceCulture);
            }
        }
    }
}
