//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestSectionStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestSectionStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TestSectionStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập mới.
        /// </summary>
        internal static string TestSectionCreate_New {
            get {
                return ResourceManager.GetString("TestSectionCreate_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string TestSectionCreate_Save {
            get {
                return ResourceManager.GetString("TestSectionCreate_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Nhóm Xét Nghiệm.
        /// </summary>
        internal static string TestSectionCreate_Title {
            get {
                return ResourceManager.GetString("TestSectionCreate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật Nhóm Xét Nghiệm.
        /// </summary>
        internal static string TestSectionEdit_Title {
            get {
                return ResourceManager.GetString("TestSectionEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string TestSectionSearch_IsActive {
            get {
                return ResourceManager.GetString("TestSectionSearch_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Nhóm.
        /// </summary>
        internal static string TestSectionSearch_Name {
            get {
                return ResourceManager.GetString("TestSectionSearch_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Nhóm Xét Nghiệm.
        /// </summary>
        internal static string TestSectionSearch_Title {
            get {
                return ResourceManager.GetString("TestSectionSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá.
        /// </summary>
        internal static string TestSection_Cost {
            get {
                return ResourceManager.GetString("TestSection_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mô tả.
        /// </summary>
        internal static string TestSection_Description {
            get {
                return ResourceManager.GetString("TestSection_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kích Hoạt.
        /// </summary>
        internal static string TestSection_IsActive {
            get {
                return ResourceManager.GetString("TestSection_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhóm xét nghiệm.
        /// </summary>
        internal static string TestSection_ListTitle {
            get {
                return ResourceManager.GetString("TestSection_ListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Nhóm.
        /// </summary>
        internal static string TestSection_Name {
            get {
                return ResourceManager.GetString("TestSection_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhóm XN đã tồn tại.
        /// </summary>
        internal static string TestSection_NameError {
            get {
                return ResourceManager.GetString("TestSection_NameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sắp xếp.
        /// </summary>
        internal static string TestSection_SortOrder {
            get {
                return ResourceManager.GetString("TestSection_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sử dụng giá chung cho XN nằm trong nhóm.
        /// </summary>
        internal static string VMTestSection_UseCostForAssociateTest {
            get {
                return ResourceManager.GetString("VMTestSection_UseCostForAssociateTest", resourceCulture);
            }
        }
    }
}
