//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PatientStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PatientStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string PatientAddress {
            get {
                return ResourceManager.GetString("PatientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        internal static string PatientBirthday {
            get {
                return ResourceManager.GetString("PatientBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn xét nghiệm.
        /// </summary>
        internal static string PatientCreate_TestRequired {
            get {
                return ResourceManager.GetString("PatientCreate_TestRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Bệnh Nhân.
        /// </summary>
        internal static string PatientCreate_Title {
            get {
                return ResourceManager.GetString("PatientCreate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chẩn Đoán.
        /// </summary>
        internal static string PatientDiagnosis {
            get {
                return ResourceManager.GetString("PatientDiagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập Nhật Thông Tin Bệnh Nhân.
        /// </summary>
        internal static string PatientEdit_Title {
            get {
                return ResourceManager.GetString("PatientEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string PatientEmail {
            get {
                return ResourceManager.GetString("PatientEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới Tính.
        /// </summary>
        internal static string PatientGender {
            get {
                return ResourceManager.GetString("PatientGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        internal static string PatientIDNumber {
            get {
                return ResourceManager.GetString("PatientIDNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hủy.
        /// </summary>
        internal static string PatientInsert_Button_Cancel {
            get {
                return ResourceManager.GetString("PatientInsert_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        internal static string PatientInsert_Button_Save {
            get {
                return ResourceManager.GetString("PatientInsert_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn Panel XN cho BN.
        /// </summary>
        internal static string PatientInsert_Panel {
            get {
                return ResourceManager.GetString("PatientInsert_Panel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi gửi mẫu.
        /// </summary>
        internal static string PatientInsert_Partner {
            get {
                return ResourceManager.GetString("PatientInsert_Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày Nhận.
        /// </summary>
        internal static string PatientInsert_ReceivedDate {
            get {
                return ResourceManager.GetString("PatientInsert_ReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thông tin bệnh nhân.
        /// </summary>
        internal static string PatientInsert_Title {
            get {
                return ResourceManager.GetString("PatientInsert_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại.
        /// </summary>
        internal static string PatientPhone {
            get {
                return ResourceManager.GetString("PatientPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm Bệnh Nhân.
        /// </summary>
        internal static string PatientSearch_Title {
            get {
                return ResourceManager.GetString("PatientSearch_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm số thứ tự.
        /// </summary>
        internal static string PatientSTT {
            get {
                return ResourceManager.GetString("PatientSTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền Kết Quả XN.
        /// </summary>
        internal static string PatientTestUpdate_Title {
            get {
                return ResourceManager.GetString("PatientTestUpdate_Title", resourceCulture);
            }
        }
    }
}
