//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GlobalStrings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ Thống Quản Lý Phòng Lab.
        /// </summary>
        internal static string LabnetClientTitle {
            get {
                return ResourceManager.GetString("LabnetClientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Bác Sĩ.
        /// </summary>
        internal static string Menu_CreateDoctor {
            get {
                return ResourceManager.GetString("Menu_CreateDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Lab Gửi Mẫu.
        /// </summary>
        internal static string Menu_CreateLabPartner {
            get {
                return ResourceManager.GetString("Menu_CreateLabPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Xét Nghiệm.
        /// </summary>
        internal static string Menu_CreateTest {
            get {
                return ResourceManager.GetString("Menu_CreateTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm Panel XN.
        /// </summary>
        internal static string Menu_CreateTestPanel {
            get {
                return ResourceManager.GetString("Menu_CreateTestPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Tài Chính.
        /// </summary>
        internal static string Menu_FinancialBook {
            get {
                return ResourceManager.GetString("Menu_FinancialBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Lab Gửi Mẫu.
        /// </summary>
        internal static string Menu_GroupTitle_Lab {
            get {
                return ResourceManager.GetString("Menu_GroupTitle_Lab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Bệnh Nhân.
        /// </summary>
        internal static string Menu_GroupTitle_Patient {
            get {
                return ResourceManager.GetString("Menu_GroupTitle_Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý PXN.
        /// </summary>
        internal static string Menu_GroupTitle_PXN {
            get {
                return ResourceManager.GetString("Menu_GroupTitle_PXN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống Kê - Báo Cáo.
        /// </summary>
        internal static string Menu_GroupTitle_Report {
            get {
                return ResourceManager.GetString("Menu_GroupTitle_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản Lý Nhân Sự.
        /// </summary>
        internal static string Menu_Management {
            get {
                return ResourceManager.GetString("Menu_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống Kê Hóa Chất.
        /// </summary>
        internal static string Menu_MaterialBook {
            get {
                return ResourceManager.GetString("Menu_MaterialBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Chính.
        /// </summary>
        internal static string Menu_MenuTitle {
            get {
                return ResourceManager.GetString("Menu_MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông Tin Bệnh Nhân.
        /// </summary>
        internal static string Menu_PatientInfo {
            get {
                return ResourceManager.GetString("Menu_PatientInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Kết Quả XN.
        /// </summary>
        internal static string Menu_PatientResult {
            get {
                return ResourceManager.GetString("Menu_PatientResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sổ Lưu Kết Quả.
        /// </summary>
        internal static string Menu_ResultBook {
            get {
                return ResourceManager.GetString("Menu_ResultBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Bác Sĩ.
        /// </summary>
        internal static string Menu_SearchDoctor {
            get {
                return ResourceManager.GetString("Menu_SearchDoctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Lab.
        /// </summary>
        internal static string Menu_SearchPartnerCost {
            get {
                return ResourceManager.GetString("Menu_SearchPartnerCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Kiếm Bệnh Nhân.
        /// </summary>
        internal static string Menu_SearchPatients {
            get {
                return ResourceManager.GetString("Menu_SearchPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Xét Nghiệm.
        /// </summary>
        internal static string Menu_SearchTest {
            get {
                return ResourceManager.GetString("Menu_SearchTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm Panel .
        /// </summary>
        internal static string Menu_SearchTestPanel {
            get {
                return ResourceManager.GetString("Menu_SearchTestPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điền Kết Quả XN.
        /// </summary>
        internal static string Menu_UpdateTestResult {
            get {
                return ResourceManager.GetString("Menu_UpdateTestResult", resourceCulture);
            }
        }
    }
}
